name: CD - Build & Publish OCI to GHCR

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/j4c62/pms-property-service

jobs:
  release-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Generate version from timestamp
        id: tagger
        run: |
          VERSION=$(date +'%Y.%m.%d.%H%M%S')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Set version in gradle.properties
        run: echo "version=${{ steps.tagger.outputs.version }}" > gradle.properties

      - name: Build & Publish OCI image
        run: |
          ./gradlew bootBuildImage \
            --imageName=${{ env.IMAGE_NAME }}:${{ env.VERSION }} \
            --no-daemon

      - name: Push image to GitHub Container Registry
        run: docker push ${{ env.IMAGE_NAME }}:${{ env.VERSION }}

      - name: Generate Release Notes
        id: changelog
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
          if [ -n "$LAST_TAG" ]; then
            LOG=$(git log "$LAST_TAG"..HEAD --pretty=format:"- %s")
          else
            LOG=$(git log --pretty=format:"- %s")
          fi
          echo "log<<EOF" >> $GITHUB_OUTPUT
          echo "$LOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Git Tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag "v${{ steps.tagger.outputs.version }}"
          git push origin "v${{ steps.tagger.outputs.version }}"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.tagger.outputs.version }}
          name: Release v${{ steps.tagger.outputs.version }}
          body: ${{ steps.changelog.outputs.log }}
